[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "contentrepo"
version = "1.0.0-dev.2"
authors = [
  { name="Praekelt.org", email="dev@praekelt.org" },
]
description = "A CMS for messaging systems"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[project.urls]
"Homepage" = "https://github.com/praekeltfoundation/contentrepo"
"Bug Tracker" = "https://github.com/praekeltfoundation/contentrepo/issues"

[tool.setuptools]
packages = ["contentrepo", "home", "menu", "search"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.ve
  | ve
  | env
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''
