[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "contentrepo"
version = "1.1.0-dev.3"
authors = [
  { name="Praekelt.org", email="dev@praekelt.org" },
]
description = "A CMS for messaging systems"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies", "optional-dependencies"]

[project.urls]
"Homepage" = "https://github.com/praekeltfoundation/contentrepo"
"Bug Tracker" = "https://github.com/praekeltfoundation/contentrepo/issues"

[tool.setuptools]
packages = ["contentrepo", "home", "menu", "search"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
optional-dependencies.dev = {file = ["requirements-dev.txt"]}

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.ve
  | ve
  | env
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.mypy]
files = "home/import_content_pages.py,home/tests/helpers.py,home/tests/page_builder.py,home/tests/test_content_import_export.py,home/tests/test_page_builder.py"
follow_imports = "skip"
disallow_untyped_defs = true
disallow_any_generics = true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "contentrepo.settings.dev"
addopts = "--cov"
filterwarnings = [
    # We can't do anything about these warnings until upstream updates.
    "ignore::django.utils.deprecation.RemovedInDjango50Warning:modelcluster.models:28",
    "ignore::DeprecationWarning:l18n.translation:17",
    "ignore::DeprecationWarning:wagtail.images.views.serve:1",
]

[tool.ruff]
select = [
    "E", "F", "W", # pycodestyle + pyflakes == flake8 - mccabe
    "I",           # isort
    # "UP",          # pyupgrade
    "S",           # flake8-bandit
    "B",           # flake8-bugbear
    "C4",          # flake8-comprehensions
    # "DJ",          # flake8-django
    "PIE",         # flake8-pie
    # "PT",          # flake8-pytest-style
    "SIM",         # flake8-simplify
    "PTH",         # flake8-use-pathlib
    # "RUF",         # ruff-specific rules
]
target-version = "py310"
ignore = [
    "E501",  # TODO: Something about these long lines.
    "S113",  # TODO: Request timeouts.
    "B904",  # TODO: Fix exceptions raised in exception handlers.
    "SIM102",  # It's often more convenient/readable to use nested conditionals.
    "SIM117",  # It's often more convenient/readable to use nested context managers.
    "SIM115",  # TODO: Fix non-context-manager open() calls.
]

[tool.ruff.per-file-ignores]
"contentrepo/settings/**" = [
    "S105",  # TODO: Get rid of default DEFAULT_SECRET_KEY.
    "F405",  # We import * in settings files.
    "PTH",  # TODO: Use pathlib in settings.
]
"**/tests/**" = [
    "S101",  # It's okay to use `assert` in tests.
]
"**/migrations/**" = [
    "E501",  # Long lines are okay in generated code.
]
