name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.16
        env:
          POSTGRES_DB: contentrepo
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      CONTENTREPO_DATABASE: postgres://postgres:postgres@localhost:5432/contentrepo
    strategy:
      matrix:
        python-version: [3.10.6]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      id: install-deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Check formatting
      # Lints/tests should always run, even if other lints/tests have failed.
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        black --check .
        exit 1  # FIXME: Temp failure to check that future steps run.
    - name: Lint
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        ruff .
    - name: Check types
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        mypy
    - name: Run tests
      if: success() || failure() && steps.install-deps.outcome == 'success'
      run: |
        pytest -vv
